# Makefile for compiling eps-moea source code
CC=gcc
LD=gcc
RM=rm -f
CFLAGS=-Wall -Werror -ansi -pedantic -g
LDFLAGS=-Wall
OBJS:=$(patsubst %.c,%.o,$(wildcard *.c))
MAIN=main
all:$(MAIN)
$(MAIN):$(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) -o $(MAIN) -lm
%.o: %.c global.h rand.h
	$(CC) $(CFLAGS) -c $<
clean:
	$(RM) $(OBJS)

